version: '3.8'
services:
  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: allfather_secure
      POSTGRES_DB: allfather_data
    volumes:
      - ./Database.sql:/docker-entrypoint-initdb.d/Database.sql

  python_brain:
    build: ./python_brain
    ports:
      - "8050:8050"
    depends_on:
      - db

  go_gateway:
    build: ./go_gateway
    ports:
      - "8080:8080"
